### ISSUE TITLE
 "status": "FROM_NOT_FOUND"

### ISSUE THREAD

**Issue by negati-ve** [felipeDS91/whatsapp-api#4]
I'm copying the phone field returned from querying the GET /tokens route as the from field for POST /messages route

GET /messages returns  "status": "FROM_NOT_FOUND"

please clarify what should be used in the from field for GET /messages

**Comment by negati-ve** [comment]
figured.

So, the documentation/README should mention that DEFAULT_DDI in .env file dictates the country code and the whatsapp api will only work for that specified country 

from and to field should be without country code for now, correct?

**Comment by felipeDS91** [comment]
Yes, you have to fill DEFAULT_DDI env

**Comment by fablunardi** [comment]
Oi Felipe. Quando eu faço um {{ base_url }}/tokens/ scaneio o qrcode, mas não vejo nenhum registro na tabela tokens. O que será estou fazendo de errado?

**Comment by felipeDS91** [comment]
> Oi Felipe. Quando eu faço um {{ base_url }}/tokens/ scaneio o qrcode, mas não vejo nenhum registro na tabela tokens. O que será estou fazendo de errado?

Problema solucionado

**Comment by fablunardi** [comment]
Oi Felipe, Obrigado pela atualização.
Atualizei o código e mesmo assim, depois de scanear o QR Code via terminal, depois de alguns segundos recebo "read qrcode timeout reached" e não vejo nada na tabela tokens. Não sei se estou fazendo algo errado ou se está falando alguma ação minha depois que scanear o código.

Obrigado!
