### ISSUE TITLE
Why can't send to national numbers ?

### ISSUE THREAD

**Issue by Momaiz** [felipeDS91/whatsapp-api#7]
Hello , 
Why i can't send to national numbers . 
i changed 
DEFAULT_DDI=
but  can't send ?

**Comment by felipeDS91** [comment]
I dont' know the pattern of your country, but here in my country you have to fill the phone number with "DDI + DDD + Phone Number" where DDI = Direct Dial Inward and DDD = direct distance dialing.

**Comment by Momaiz** [comment]
Thank you for answer @felipeDS91 
My Code is 020 and i use it  as  DEFAULT_DDI=20
it work perfect . 
But i need to send to  other countries  like 966
I changed some code to ignore DEFAULT_DDI and use it direct from number
but message sent  with 
![image](https://user-images.githubusercontent.com/20012757/115125398-18021f80-9fc8-11eb-843f-01b159853d28.png)
with No name - subject "ubknown subject"

**Comment by felipeDS91** [comment]
When I did this project my goal was to send message only in my country, so because of that I created this variable. You will need to remove this variable and receive it in the body of the request.

**Comment by Momaiz** [comment]
Thank you @felipeDS91 .
I will check it .
Best regards
